apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: default
spec:
  clusterIP: 10.233.20.27
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  type: NodePort
