---
- hosts: localhost
  tasks:

    # Edit all.yml variable file
    - name: Add lines to the all.yaml variable file
      lineinfile:
        path: inventories/{{ deployment_name }}/group_vars/all/all.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^ansible_python_interpreter:.*$', line: 'ansible_python_interpreter: /usr/bin/python3' }
        - { regexp: '^ansible_user:.*$', line: 'ansible_user: {{ ssh_user }}' }
        - { regexp: '^ansible_become:.*$', line: 'ansible_become: true' }
        - { regexp: '^ansible_ssh_pass:.*$', line: "ansible_ssh_pass: '{{ \"{{\" }} ssh_pass {{ \"}}\" }}'" }
        - { regexp: '^ansible_become_pass:.*$', line: "ansible_become_pass: '{{ \"{{\" }} sudo_pass {{ \"}}\" }}'" }
        - { regexp: '^ssh_pubkey:.*$', line: "ssh_pubkey: '~/.ssh/id_rsa.pub'" }

    # Edit etcd.yml variable file
    - name: Modify etcd.yml.
      lineinfile:
        path: inventories/{{ deployment_name }}/group_vars/etcd.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^etcd_deployment_type:.*$', line: 'etcd_deployment_type: {{ etcd_deployment_type }}' }

    # Edit k8s-config.yml variable file
    - name: Modify k8s-config.yml.
      lineinfile:
        path: inventories/{{ deployment_name }}/group_vars/k8s-cluster/k8s-cluster.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^kube_version:.*$', line: 'kube_version: {{ kube_version }}' }
        - { regexp: '^container_manager:.*$', line: 'container_manager: {{ container_manager }}' }
        - { regexp: 'docker_version:.*$', line: 'docker_version: "{{ docker_version }}"' }
        - { regexp: '^kube_network_plugin:.*$', line: 'kube_network_plugin: {{ kube_network_plugin }}' }
        - { regexp: '^cilium_version:.*$', line: 'cilium_version: {{ cilium_version }}' }
        - { regexp: '^helm_enabled.*$', line: 'helm_enabled: {{ helm_enabled }}' }
        - { regexp: 'kube_proxy_remove.*$', line: 'kube_proxy_remove: {{ kube_proxy_remove }}' }
        - { regexp: 'download_run_once:.*$', line: 'download_run_once: {{ download_run_once }}' }
        - { regexp: 'download_localhost:.*$', line: 'download_localhost: {{ download_localhost }}' }
        - { regexp: '^#\s*kubeconfig_localhost.*$', line: 'kubeconfig_localhost: true' }
        - { regexp: '^containerd_use_systemd_cgroup:.*$', line: 'containerd_use_systemd_cgroup: {{ containerd_use_systemd_cgroup }}' }

    # Edit k8s-net-cilium.yml variable file
    - name: Modify k8s-net-cilium.yml.
      lineinfile:
        path: inventories/{{ deployment_name }}/group_vars/k8s-cluster/k8s-net-cilium.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^cilium_kube_proxy_replacement:.*$', line: 'cilium_kube_proxy_replacement: {{ cilium_kube_proxy_replacement }}' }

#    # Edit no kube-proxy related yaml files.
#    - name: Modify kubeadm-setup.yml not to install kube-proxy
#      lineinfile:
#        path: kubespray/roles/kubernetes/master/tasks/kubeadm-setup.yml
#        insertafter: '--skip-phases=.*coredns'
#        line: '    --skip-phases=addon/kube-proxy'
#        backup: yes
#    - name: Modify kubeadm-secondary-legacy.yml not to install kube-proxy
#      lineinfile:
#        path: kubespray/roles/kubernetes/master/tasks/kubeadm-secondary-legacy.yml
#        regexp: '^(.*--skip-phases=.*coredns)$'
#        line: '\1 --skip-phases=addon/kube-proxy'
#        backup: yes
#        backrefs: yes
...
